"""
physiology_boundaries.py — Architectural Boundaries: ML Inputs vs. Deterministic Sports Science Engine

This module defines and validates the explicit boundary between:
  1. Task 1A (ML Performance Model): Pacing, finish-time projection, and environmental slowdown
  2. Task 1B (Deterministic Sports Science Engine): VO2 demand, substrate oxidation, glycogen depletion, and nutrition

Architectural Boundary:
  - Task 1A DOES NOT consume granular metabolic rates or glycogen stores.
  - Task 1B DOES NOT use neural network weights; it executes deterministic, peer-reviewed
    equations (ACSM, Péronnet & Massicotte, Minetti, Uth HR ratio, Jeukendrup carbohydrate rates).
  - Task 1A outputs (race pace and finish duration) feed directly as deterministic inputs into Task 1B.
"""

from typing import Optional, Dict, Any
from pydantic import BaseModel, Field

# ===================================================================
# 1. Task 1A: Machine Learning Performance Model
# ===================================================================

class Task1AMLInputs(BaseModel):
    """
    Features strictly fed into the Task 1A Machine Learning / Empirical Pacing Model.
    Mixes demographic anchors, recent performance, longitudinal training state,
    and route-specific environmental variables.
    """
    # Runner Baseline Anchor
    age: int = Field(..., ge=16, le=100, description="Chronological age in years")
    sex: str = Field(..., description="'M' / 'W' or 'male' / 'female'")
    split_hhmmss: str = Field(..., description="Half marathon split time or baseline anchor (HH:MM:SS)")
    
    # Longitudinal Training Features (Learned / Dynamic State)
    chronic_weekly_avg_km: Optional[float] = Field(40.0, description="Rolling 28-day weekly average volume")
    rolling_longest_run_4w_km: Optional[float] = Field(16.0, description="Longest run in previous 4 weeks")
    acwr: Optional[float] = Field(1.0, description="Acute:Chronic Workload Ratio")
    
    # Environmental & Course Features
    course_difficulty_score: Optional[float] = Field(0.0, description="Terrain difficulty score")
    net_elevation_m: Optional[float] = Field(0.0, description="Net course elevation change in meters")
    effective_headwind_mps: Optional[float] = Field(0.0, description="Course-relative headwind component")
    wbgt_c: Optional[float] = Field(15.0, description="Wet Bulb Globe Temperature in Celsius")

class Task1AMLOutputs(BaseModel):
    """
    Predictions produced by the Task 1A model that serve as deterministic anchors for Task 1B.
    """
    predicted_finish_seconds: int
    predicted_finish_time: str           # "HH:MM:SS"
    predicted_pace_kmh: float            # Speed in km/h
    target_pace_minkm: str               # "MM:SS /km"
    environmental_slowdown_pct: float    # Combined slowdown from heat, wind, and hills
    time_added_seconds: int


# ===================================================================
# 2. Task 1B: Deterministic Sports Science & Nutrition Engine
# ===================================================================

class Task1BDeterministicInputs(BaseModel):
    """
    Inputs fed strictly into the deterministic sports science and metabolic engine.
    Combines Task 1A outputs with the athlete's biometrics and physiological baselines.
    """
    # Generated by Task 1A
    target_pace_kmh: float = Field(..., description="Target race speed generated by Task 1A")
    predicted_finish_seconds: int = Field(..., description="Finish duration from Task 1A")
    distance_km: float = Field(42.195, description="Race distance")

    # Physiological Baseline Parameters
    weight_kg: float = Field(..., ge=35.0, le=160.0, description="Body mass in kilograms")
    height_cm: float = Field(..., ge=120.0, le=230.0, description="Height in centimeters")
    sex: int = Field(1, description="1 = male, 0 = female")
    resting_hr_bpm: float = Field(52.0, ge=30, le=100, description="Resting heart rate")
    max_hr_bpm: float = Field(188.0, ge=120, le=230, description="Maximum heart rate")

    # Advanced / Tested Baselines (Optional - defaults to physiological equations if omitted)
    vo2max_ml_kg_min: Optional[float] = Field(None, description="Direct lab or calibrated VO2max")
    body_fat_pct: Optional[float] = Field(None, description="Body fat percentage for FFM calculation")
    lt_hr_bpm: Optional[int] = Field(None, description="Lactate threshold heart rate")
    is_carb_loaded: bool = Field(True, description="Whether athlete follows pre-race carbohydrate loading protocol")
    
    # Environmental Context (for thermoregulation and sweating)
    temperature_c: float = Field(15.0, description="Ambient race temperature")
    course_ascent_m: float = Field(0.0, description="Course total ascent for mechanical work adjustment")

class Task1BDeterministicOutputs(BaseModel):
    """
    Metabolic and nutritional outputs calculated via deterministic peer-reviewed formulas.
    """
    vo2_demand_ml_kg_min: float         # ACSM running metabolic equation
    pct_vo2max: float                   # Exercise intensity as % of aerobic capacity
    rer: float                          # Respiratory exchange ratio
    cho_oxidation_g_hr: float           # Carbohydrate oxidation rate
    fat_oxidation_g_hr: float           # Fat oxidation rate
    total_energy_kcal_min: float        # Caloric burn rate
    total_race_cho_burned_g: float      # Total race carbohydrate demand
    glycogen_depletion_point_km: float  # Estimated distance where endogenous glycogen is exhausted
    wall_risk: str                      # 'LOW', 'MODERATE', 'HIGH'
    recommended_carbs_g_per_h: float    # In-race fueling target (30-90 g/h)
    recommended_fluid_ml_per_h: float   # In-race fluid intake
    recommended_sodium_mg_per_h: float  # In-race electrolyte target
