import { useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

export const Route=createFileRoute("/_authenticated/onboarding")({head:()=>({meta:[{title:"Set up your profile — Stride"},{name:"description",content:"Set your athlete details, units, and data consent preferences."},{property:"og:title",content:"Set up Stride"},{property:"og:description",content:"Configure your private athlete profile."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Onboarding});
const consentOptions = [{key:"training" as const,title:"Training data",copy:"Use sessions and volume to calculate projections."},{key:"nutrition" as const,title:"Nutrition data",copy:"Use fueling logs to personalize race plans."},{key:"research" as const,title:"Anonymous research",copy:"Contribute de-identified data to model validation."}];
function Onboarding(){const navigate=useNavigate();const[step,setStep]=useState(1);const[age,setAge]=useState(31);const[mass,setMass]=useState(64);const[sex,setSex]=useState("open");const[units,setUnits]=useState("metric");const[consent,setConsent]=useState({training:true,nutrition:true,research:false});const[busy,setBusy]=useState(false);
async function finish(){setBusy(true);const{data}=await supabase.auth.getUser();if(!data.user){setBusy(false);return}await supabase.from("profiles").upsert({user_id:data.user.id,age,body_mass_kg:mass,sex_category:sex,unit_preference:units,consent_training:consent.training,consent_nutrition:consent.nutrition,consent_research:consent.research,onboarding_complete:true});const role=localStorage.getItem("stride_pending_role")||"athlete";await supabase.from("user_roles").upsert({user_id:data.user.id,role:role==="coach"?"coach":"athlete"},{onConflict:"user_id,role"});await navigate({to:role==="coach"?"/coach":"/app"});}
return <main className="min-h-screen px-4 py-8 sm:py-14"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><span className="font-mono text-xl font-semibold">STRIDE</span><span className="font-mono text-xs text-muted-foreground">STEP {step} / 3</span></div><div className="mt-6 flex gap-2">{[1,2,3].map(n=><span key={n} className={`h-1 flex-1 ${n<=step?"bg-primary":"bg-border"}`}/>)}</div><section className="mt-10 border border-border bg-card p-6 shadow-[var(--shadow-panel)] sm:p-9">{step===1&&<><p className="font-mono text-xs uppercase text-primary">Baseline</p><h1 className="mt-2 text-3xl font-semibold">Your profile</h1><p className="mt-2 text-sm text-muted-foreground">Used to calibrate projections and fueling estimates.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label>Age</Label><Input type="number" min={16} max={100} value={age} onChange={e=>setAge(Math.max(16,Math.min(100,Number(e.target.value)||16)))}/></div><div className="space-y-2"><Label>Body mass (kg)</Label><Input type="number" min={35} max={300} value={mass} onChange={e=>setMass(Math.max(35,Math.min(300,Number(e.target.value)||35)))}/></div><div className="space-y-2 sm:col-span-2"><Label>Sex category</Label><Select value={sex} onValueChange={setSex}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="female">Female</SelectItem><SelectItem value="male">Male</SelectItem><SelectItem value="open">Open</SelectItem></SelectContent></Select></div></div></>}{step===2&&<><p className="font-mono text-xs uppercase text-primary">Preferences</p><h1 className="mt-2 text-3xl font-semibold">Choose your units</h1><div className="mt-8 grid grid-cols-2 gap-3">{["metric","imperial"].map(u=><Button key={u} variant={units===u?"default":"outline"} className="h-20 capitalize" onClick={()=>setUnits(u)}>{u}<span className="text-xs opacity-60">{u==="metric"?"km · kg":"mi · lb"}</span></Button>)}</div></>}{step===3&&<><p className="font-mono text-xs uppercase text-primary">Privacy</p><h1 className="mt-2 text-3xl font-semibold">Your data, by choice</h1><p className="mt-2 text-sm text-muted-foreground">Change these permissions whenever you want.</p><div className="mt-8 divide-y divide-border">{consentOptions.map(({key,title,copy})=><div key={key} className="flex items-center gap-4 py-5"><div className="flex-1"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{copy}</p></div><Switch checked={consent[key]} onCheckedChange={v=>setConsent({...consent,[key]:v})}/></div>)}</div></>}<div className="mt-9 flex justify-between"><Button variant="ghost" disabled={step===1} onClick={()=>setStep(step-1)}><ArrowLeft/>Back</Button>{step<3?<Button onClick={()=>setStep(step+1)}>Continue<ArrowRight/></Button>:<Button onClick={finish} disabled={busy}>{busy?"Saving…":<>Finish setup<Check/></>}</Button>}</div></section></div></main>}