/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedFuelRouteImport } from './routes/_authenticated/fuel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedRacePlansRouteImport } from './routes/_authenticated/race-plans'
import { Route as AuthenticatedTrainRouteImport } from './routes/_authenticated/train'
import { Route as AuthenticatedCoachReviewsRouteImport } from './routes/_authenticated/coach.reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuelRoute = AuthenticatedFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRacePlansRoute = AuthenticatedRacePlansRouteImport.update({
  id: '/race-plans',
  path: '/race-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainRoute = AuthenticatedTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachReviewsRoute =
  AuthenticatedCoachReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/connect': typeof AuthenticatedConnectRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/race-plans': typeof AuthenticatedRacePlansRoute
  '/train': typeof AuthenticatedTrainRoute
  '/coach/reviews': typeof AuthenticatedCoachReviewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/connect': typeof AuthenticatedConnectRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/fuel': typeof AuthenticatedFuelRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/race-plans': typeof AuthenticatedRacePlansRoute
  '/train': typeof AuthenticatedTrainRoute
  '/coach/reviews': typeof AuthenticatedCoachReviewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/fuel': typeof AuthenticatedFuelRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/race-plans': typeof AuthenticatedRacePlansRoute
  '/_authenticated/train': typeof AuthenticatedTrainRoute
  '/_authenticated/coach/reviews': typeof AuthenticatedCoachReviewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/coach'
    | '/connect'
    | '/devices'
    | '/fuel'
    | '/onboarding'
    | '/race-plans'
    | '/train'
    | '/coach/reviews'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/coach'
    | '/connect'
    | '/devices'
    | '/fuel'
    | '/onboarding'
    | '/race-plans'
    | '/train'
    | '/coach/reviews'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/coach'
    | '/_authenticated/connect'
    | '/_authenticated/devices'
    | '/_authenticated/fuel'
    | '/_authenticated/onboarding'
    | '/_authenticated/race-plans'
    | '/_authenticated/train'
    | '/_authenticated/coach/reviews'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fuel': {
      id: '/_authenticated/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof AuthenticatedFuelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/race-plans': {
      id: '/_authenticated/race-plans'
      path: '/race-plans'
      fullPath: '/race-plans'
      preLoaderRoute: typeof AuthenticatedRacePlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/train': {
      id: '/_authenticated/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof AuthenticatedTrainRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/reviews': {
      id: '/_authenticated/coach/reviews'
      path: '/reviews'
      fullPath: '/coach/reviews'
      preLoaderRoute: typeof AuthenticatedCoachReviewsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
  }
}

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachReviewsRoute: typeof AuthenticatedCoachReviewsRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachReviewsRoute: AuthenticatedCoachReviewsRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedFuelRoute: typeof AuthenticatedFuelRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRacePlansRoute: typeof AuthenticatedRacePlansRoute
  AuthenticatedTrainRoute: typeof AuthenticatedTrainRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedFuelRoute: AuthenticatedFuelRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRacePlansRoute: AuthenticatedRacePlansRoute,
  AuthenticatedTrainRoute: AuthenticatedTrainRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
